### ISSUE TITLE
Extension and encoding

### ISSUE THREAD

**Issue by dchusovitin** [sourcegraph/sourcegraph-browser-extensions#11]
Extension breaks russian characters in UTF-8 encoding.
Tested in incognito mode only with SourceGraph extension.

Demo link: https://github.com/anti-censorship-russia/chromium-extension/blob/master/extensions/chromium/minimalistic-pac-setter/extension/3-context-menus.js

**With extension:**
![with_sourcegraph](https://cloud.githubusercontent.com/assets/371252/16715886/53c22b7c-46f5-11e6-8d4a-1fb31bd725e8.png)

**Without extension:**
![without_sourcegraph](https://cloud.githubusercontent.com/assets/371252/16715887/55b5c998-46f5-11e6-96cb-1ced0e1ef0d6.png)

**Comment by uforic** [comment]
Hey @dchusovitin , can you see if this is still an issue? I checked another repository with some of the encoded text in your repository, https://github.com/uforic-test/public-test/blob/master/reverse.go , and don't see this issue.

Closing for now, but definitely re-open if it is still a problem.
