### ISSUE TITLE
Chrome extension partially interprets HTML in code views?

### ISSUE THREAD

**Issue by juliusv** [sourcegraph/sourcegraph-browser-extensions#12]
See https://github.com/prometheus/mysqld_exporter/blob/master/mysqld_exporter.go#L141

This is what it looks like without the Sourcegraph extension:

![correct](https://cloud.githubusercontent.com/assets/538008/18886012/72602a20-84ee-11e6-93ad-2f99dabf3cc2.png)

And this is what the Sourcegraph extension makes out of it:

![html_handling](https://cloud.githubusercontent.com/assets/538008/18885963/38f683a6-84ee-11e6-8f4c-7956c872414f.png)

Is that intentional? Now I tried injecting a `<script>` or `<style>` and that *didn't* work (which is good), but that makes me think that there's some filtering going on and this might all be intentional? Would seem a bit odd though...

**Comment by zeusk** [comment]
This is not intentional, looking into it. Thanks for the report!
