### ISSUE TITLE
Unicode characters got broken

### ISSUE THREAD

**Issue by rokoroku** [sourcegraph/sourcegraph-browser-extensions#14]
With sourcegraph chrome extension, Unicode characters on GitHub source files are broken.

### Expected

<img width="622" alt="2017-02-24 5 44 13" src="https://cloud.githubusercontent.com/assets/5208632/23296541/e95ef788-fab8-11e6-89a8-8e46d846f615.png">

### Actual

<img width="648" alt="2017-02-24 5 44 03" src="https://cloud.githubusercontent.com/assets/5208632/23296542/ea0adeae-fab8-11e6-8a84-84ddfc43d165.png">

Link to above sample: 
https://github.com/open-korean-text/open-korean-text-wrapper-node-2/blob/master/test/tokens.spec.js

**Comment by uforic** [comment]
Thanks for reporting, @rokoroku ! We are reverting a change that caused this tomorrow.

**Comment by uforic** [comment]
Hey @rokoroku , just double checked, and the latest deployment of the Chrome extension fixed this. Thanks again for reporting!
