### ISSUE TITLE
New tree view conflicts with OctoTree

### ISSUE THREAD

**Issue by fritzo** [sourcegraph/sourcegraph-browser-extensions#18]
Would it be possible to detect if OctoTree extension is installed? I really like the OctoTree view, and cannot currently use the Sourcegraph extension due to this conflict.

**Comment by KattMingMing** [comment]
@fritzo - In the most recent version released it should automatically detect that Octotree is installed. However, you can also click on the Sourcegraph icon and uncheck Enable repository file tree. Hope this helps!

https://photos-2.dropbox.com/t/2/AAB3HOmy2hebEqHOcllaEzw7z7vux8FMjoV7eo-n_jug4g/12/52988715/png/32x32/1/_/1/2/Screenshot%202017-08-08%2014.47.04.png/ENal7SgYrekbIAcoBw/MnNvVUk5i3OXnMxGvvJ5V59Re6qiyLzPlIfseFTB7TQ?size=2048x1536&size_mode=3

**Comment by fritzo** [comment]
Oh, thanks!
