### ISSUE TITLE
404 when you hit "Last processed revision" in a file that does not exist in that revision

### ISSUE THREAD

**Issue by samertm** [sourcegraph/sourcegraph-browser-extensions#2]
To reproduce (if the build hasn't finished yet):
1. Go to 'github.com/samertm/sheep-mmo/blob/master/engine/flower.go'
2. Click 'Last processed revision'
3. You're taken to 'https://sourcegraph.com/github.com/samertm/sheep-mmo@90752d10ba840000e9155ad27a2906797c72eb05/.tree/engine/flower.go', which shows the '404 not found' page

If the build has finished, you can reproduce this issue by taking a project that's been built, adding a new file to the github project, and then clicking 'Last processed revision' on that file.

Maybe you should be taken to the closest existing parent directory? So you could climb up the tree to "engine" and display that directory, along with an error message explaining that flower.go does not exist. I'm not sure if this functionality should be part of the extension or the website.

**Comment by uforic** [comment]
Last processed revision link no longer exists; I was able to get code intelligence on the above repo. Closing out.
