### ISSUE TITLE
Perform actions on GitHub without redirecting

### ISSUE THREAD

**Issue by icylogic** [sourcegraph/sourcegraph-browser-extensions#20]
The screenshot on Chrome Web Store indicates that at least we can do some search in the side pane while browsing GitHub. 
![](https://lh3.googleusercontent.com/5UKb5z1oLz3-XgNqIlFZIHpE6grmIFiSdCn_6tQSA0_8QDCy6lWITANd6axwsTtn83CZ9W22tA=w640-h400-e365)

But now there is only a file tree. Search, Go To Definition and Find References will be redirected to sourcegraph.com. I'm new to sourcegraph, so I don't know if I'm missing something, but I couldn't find relevant information on Chrome Web Store, issues in this repo or any change notes.

Is it possible that I
1. view source code on GitHub
2. hover on something interesting
3. click Go To Definition
4. get a new github page that contains the definition?

Now in the final step I would be redirected to sourcegraph.com/something-definition and then click `View on GitHub` to jump back to GitHub.

BTW, what is the advanced option `Sourcegraph URL` for?

PS. The video in `readme.md` could not be played (https://github.com/sourcegraph/sourcegraph-browser-extensions/blob/master/README.md)

**Comment by attfarhan** [comment]
The search feature no longer lives in the file tree, but instead takes over the GitHub search bar in the header.  You can toggle this on and off by clicking the Sourcegraph logo.  We'll update the screenshot soon, thanks for bringing this up!

Our extension currently only supports jumping to Sourcegraph. We are considering other options for the future, but at the moment the extension is designed to bring you to Sourcegraph.

The advanced Sourcegraph URL option is for those who are running their own Sourcegraph server and want to get code intelligence from their own instance of Sourcegraph.

**Comment by icylogic** [comment]
Got it. Thanks for your awesome work.
