### ISSUE TITLE
icon and template do not seem properly on mozilla and mozilla editions

### ISSUE THREAD

**Issue by eliakorkmaz** [sourcegraph/sourcegraph-browser-extensions#21]
hi

i am using `sourcegraph` for one weeks, its cool tool but in `mozilla` extension there is a puzzle icon for the  app, and extension view/template is not properly as in chrome. I use the extension in Mozilla developer edition and also looked up for normal Mozilla but all editions do not looks good.
here is [screenshot](https://i.hizliresim.com/0G5oBV.png).

is it normal or are there are problem with CSS/HTML rendering cause mozilla engine etc?

**Comment by keegancsmith** [comment]
Hi @eliakorkmaz thanks for the report. Which version of firefox are you running?

**Comment by eliakorkmaz** [comment]
Hi @keegancsmith . for normal `Firefox` version its `57.0.2` and for `Dev` edition `58.0b10`.

**Comment by keegancsmith** [comment]
cc @KattMingMing

**Comment by nicksnyder** [comment]
@attfarhan owns the extension now

**Comment by eliakorkmaz** [comment]
same.

**Comment by attfarhan** [comment]
Thanks for the report.  Fix coming soon.
