### ISSUE TITLE
Deceptive console.error message when no builds exist

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph-browser-extensions#4]
If there are no builds, the JS error log can read:

```
Not adding Sourcegraph links to source code because status: 200 
```

200 is HTTP OK, so this doesn't make any sense.

This is because of the condition here: https://github.com/sourcegraph/sourcegraph-browser-extensions/blob/1dddb27d55c636771a2990c23b8943136170d21b/chrome/github.js#L57.

**Comment by uforic** [comment]
Closed, no longer in extension.
